%ENABLEITEMS Enable menu and toolbar items on image open

% Copyright (c) 2011-2014 ETH Zurich, 2015 FiberApp Contributors. All rights reserved.
% Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.

function enableItems(this)
menuItems = findobj('Type', 'uimenu', ...
    'Label', 'New Data', '-or', ...
    'Label', 'Image', '-or', ...
    'Label', 'Fiber Tracking');

toolbarItems = findobj('Type', 'uipushtool', ...
    'TooltipString', 'Zoom In (+)', '-or', ...
    'TooltipString', 'Zoom Out (-)', '-or', ...
    'TooltipString', 'Add Fiber (Space)', '-or', ...
    'TooltipString', 'Remove Fiber', '-or', ...
    'TooltipString', 'Fit Fiber (F)');

imParam = findobj('Enable', 'off', '-and', 'Parent', ...
    findobj('Type', 'uipanel', 'Tag', 'ImageParameters'));
maskParam = findobj('Enable', 'off', '-and', 'Parent', ...
    findobj('Type', 'uipanel', 'Tag', 'MaskParameters'));
fibTrackParam = findobj('Enable', 'off', '-and', 'Parent', ...
    findobj('Type', 'uipanel', 'Tag', 'FiberTrackingParameters'));
set([menuItems; toolbarItems; imParam; maskParam; fibTrackParam], ...
    'Enable', 'on');
